-- ============================================================================
-- 1. CONFIGURACIÓN DE CATEGORÍAS (Selectores)
-- ============================================================================
-- Crear tabla de categorías si no existe
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    icon TEXT, -- Emoji o nombre de icono
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insertar datos iniciales (Seed Data)
INSERT INTO public.categories (name, slug, icon) VALUES
    ('Restaurante', 'restaurante', '🍽️'),
    ('Bar / Pub', 'bar-pub', '🍻'),
    ('Cafetería', 'cafeteria', '☕'),
    ('Discoteca', 'discoteca', '💃'),
    ('Evento', 'evento', '🎫'),
    ('Parque / Aire Libre', 'parque', '🌳'),
    ('Museo / Cultura', 'cultura', '🏛️'),
    ('Tienda', 'tienda', '🛍️')
ON CONFLICT (slug) DO NOTHING;

-- Habilitar RLS para categorías (Lectura pública)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Categorías visibles para todos" ON public.categories;
CREATE POLICY "Categorías visibles para todos" 
ON public.categories FOR SELECT 
USING (true);

-- ============================================================================
-- 2. TABLA DE LOCALES (Venues)
-- ============================================================================
-- Asegurar que la extensión PostGIS está habilitada
CREATE EXTENSION IF NOT EXISTS postgis SCHEMA extensions;

-- Nota: Si la tabla ya existe, estos comandos IF NOT EXISTS no modificarán la estructura.
-- Se recomienda revisar si se necesita ALTER TABLE para columnas existentes que cambian de tipo.

CREATE TABLE IF NOT EXISTS public.venues (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
    -- Info Básica
    name TEXT NOT NULL,
    legal_name TEXT,
    slogan TEXT,
    overview TEXT,
    category_id BIGINT REFERENCES public.categories(id),
    
    -- Ubicación
    address_street TEXT,
    address_number TEXT,
    city TEXT,
    region_state TEXT,
    country_code VARCHAR(2) DEFAULT 'CL',
    address_display TEXT, -- Dirección completa formateada
    location GEOGRAPHY(POINT, 4326), -- Para mapas y búsquedas
    
    -- Media
    logo_url TEXT,
    cover_image_urls TEXT[], -- Array de URLs
    
    -- Detalles
    price_tier SMALLINT CHECK (price_tier BETWEEN 1 AND 4),
    avg_price_min NUMERIC,
    avg_price_max NUMERIC,
    currency_code VARCHAR(3) DEFAULT 'CLP',
    
    -- Configuración y Estado
    operational_status TEXT DEFAULT 'operational', -- operational, closed, temporarily_closed
    is_verified BOOLEAN DEFAULT false,
    is_featured BOOLEAN DEFAULT false,
    trust_tier TEXT DEFAULT 'standard', -- standard, bronze, silver, gold, platinum
    
    -- JSONB para flexibilidad futura
    opening_hours JSONB DEFAULT '{}'::jsonb,
    amenities JSONB DEFAULT '{}'::jsonb,
    payment_methods JSONB DEFAULT '{}'::jsonb,
    contact_info JSONB DEFAULT '{}'::jsonb, -- phone, email, website
    
    -- Métricas
    verified_visits_all_time BIGINT DEFAULT 0,
    rating_average NUMERIC(3, 2) DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    
    -- Auditoría
    owner_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para búsqueda
CREATE INDEX IF NOT EXISTS venues_location_idx ON public.venues USING GIST (location);
CREATE INDEX IF NOT EXISTS venues_category_id_idx ON public.venues (category_id);

-- RLS para Venues
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;

-- Lectura pública
DROP POLICY IF EXISTS "Locales visibles para todos" ON public.venues;
CREATE POLICY "Locales visibles para todos" 
ON public.venues FOR SELECT 
USING (true);

-- Escritura solo para Super Admins (o dueños, según lógica futura)
-- Por ahora permitimos insert a usuarios autenticados para probar
DROP POLICY IF EXISTS "Usuarios autenticados pueden crear locales" ON public.venues;
CREATE POLICY "Usuarios autenticados pueden crear locales" 
ON public.venues FOR INSERT 
TO authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Usuarios pueden editar sus propios locales" ON public.venues;
CREATE POLICY "Usuarios pueden editar sus propios locales" 
ON public.venues FOR UPDATE
TO authenticated
USING (auth.uid() = owner_id);

-- ============================================================================
-- 3. INSTRUCCIONES PARA STORAGE (Imágenes)
-- ============================================================================
/*
    IMPORTANTE: Supabase Storage requiere configuración manual o vía API, no solo SQL.
    
    Acción Requerida en Dashboard:
    1. Ve a Storage -> New Bucket
    2. Nombre: 'venues-media'
    3. Public: ON
    
    Opcional (si se prefiere SQL en el editor de Supabase):
    INSERT INTO storage.buckets (id, name, public) VALUES ('venues-media', 'venues-media', true) ON CONFLICT DO NOTHING;
    
    Políticas de Storage (Ejecutar en SQL Editor):
    -- Lectura pública
    CREATE POLICY "Imágenes visibles para todos" ON storage.objects FOR SELECT USING ( bucket_id = 'venues-media' );
    
    -- Escritura autenticada
    CREATE POLICY "Usuarios autenticados pueden subir imágenes" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'venues-media' );
*/
