-- ============================================================================
-- SCRIPT FINAL DE PUESTA EN MARCHA - BACKEND URBANVIBE
-- ============================================================================
-- Objetivo: Dejar 100% operativo el módulo de "Crear Local" alineado al esquema actual.
-- Referencia: esquemaddbb.md

-- 1. CATEGORÍAS (Tabla existente: public.venue_categories)
-- ----------------------------------------------------------------------------
-- Aseguramos que existan las categorías base para el selector.
-- La tabla ya tiene: id (int), name (varchar), icon_slug (varchar).
INSERT INTO public.venue_categories (name, icon_slug) VALUES
    ('Restaurante', 'restaurant'),
    ('Bar / Pub', 'bar'),
    ('Cafetería', 'cafe'),
    ('Discoteca', 'disco'),
    ('Evento', 'event'),
    ('Parque / Aire Libre', 'park'),
    ('Museo / Cultura', 'museum'),
    ('Tienda / Comercio', 'shopping')
ON CONFLICT DO NOTHING; -- No duplicar si ya existen

-- 2. UBICACIÓN (Nuevas tablas para Selectores UI)
-- ----------------------------------------------------------------------------
-- Justificación: El esquema actual usa texto libre para city/region. 
-- Para UX consistente, necesitamos tablas maestras.

-- 2.1 Países
CREATE TABLE IF NOT EXISTS public.countries (
    code CHAR(2) PRIMARY KEY, -- 'CL'
    name TEXT NOT NULL
);

INSERT INTO public.countries (code, name) VALUES ('CL', 'Chile') ON CONFLICT DO NOTHING;

-- 2.2 Regiones
CREATE TABLE IF NOT EXISTS public.regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code CHAR(2) REFERENCES public.countries(code),
    name TEXT NOT NULL
);

INSERT INTO public.regions (country_code, name) VALUES 
    ('CL', 'Región Metropolitana'),
    ('CL', 'Valparaíso'),
    ('CL', 'Biobío'),
    ('CL', 'Coquimbo'),
    ('CL', 'Araucanía')
ON CONFLICT DO NOTHING;

-- 2.3 Ciudades / Comunas
CREATE TABLE IF NOT EXISTS public.cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT REFERENCES public.regions(id),
    name TEXT NOT NULL
);

-- Seed básico para RM (Santiago)
DO $$
DECLARE
    rm_id BIGINT;
BEGIN
    SELECT id INTO rm_id FROM public.regions WHERE name = 'Región Metropolitana' LIMIT 1;
    
    IF rm_id IS NOT NULL THEN
        INSERT INTO public.cities (region_id, name) VALUES 
            (rm_id, 'Santiago'),
            (rm_id, 'Providencia'),
            (rm_id, 'Las Condes'),
            (rm_id, 'Vitacura'),
            (rm_id, 'Ñuñoa'),
            (rm_id, 'La Reina'),
            (rm_id, 'Recoleta')
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- Habilitar lectura pública para los selectores
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Paises visibles" ON public.countries;
CREATE POLICY "Paises visibles" ON public.countries FOR SELECT USING (true);

ALTER TABLE public.regions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Regiones visibles" ON public.regions;
CREATE POLICY "Regiones visibles" ON public.regions FOR SELECT USING (true);

ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Ciudades visibles" ON public.cities;
CREATE POLICY "Ciudades visibles" ON public.cities FOR SELECT USING (true);

-- 3. LOCALES (Tabla existente: public.venues)
-- ----------------------------------------------------------------------------
-- Política de Escritura (Insert) para usuarios autenticados
-- (Necesaria para que el formulario funcione)
DROP POLICY IF EXISTS "Usuarios autenticados pueden crear locales" ON public.venues;
CREATE POLICY "Usuarios autenticados pueden crear locales" 
ON public.venues FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- 4. STORAGE (Imágenes)
-- ----------------------------------------------------------------------------
-- Instrucciones para el Dashboard de Supabase (No SQL):
-- 1. Crear Bucket público: 'venues-media'
-- 2. Políticas RLS para 'venues-media':
--    - SELECT: true (Público)
--    - INSERT: authenticated (Solo usuarios logueados)
